# Generated by Django 5.0.2 on 2025-03-12 06:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_notification_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Threshold at which warnings are sent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_notify_student', models.BooleanField(default=True)),
                ('auto_notify_faculty', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marking_method',
            field=models.CharField(choices=[('manual', 'Marked Manually'), ('qr', 'QR Code Scan'), ('rfid', 'RFID Scan'), ('face', 'Face Recognition'), ('auto', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='session_qrcodes/'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular Class'), ('lab', 'Laboratory'), ('tutorial', 'Tutorial'), ('extra', 'Extra Class'), ('makeup', 'Makeup Class')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='student_qrcodes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Administrator')], max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancepolicy'),
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('student', 'Individual Student'), ('course', 'Course Report'), ('department', 'Department Report'), ('custom', 'Custom Report')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='attendance_reports/')),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.course')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
